### ISSUE TITLE
Very useless without an entrance and exit

### ISSUE THREAD

**Issue by trsh** [thejoshwolfe/maze-generator#17]
:((

**Comment by thejoshwolfe** [comment]
Click on "Be Done" in the "Longest Path" section, and it will highlight two points in the map that can serve as a start and end point. They aren't necessarily on the edge, so I wouldn't call them an "entrance" and "exit", but they should be able to serve the same purpose.

Also worth noting that this project isn't really trying to be "useful". It's more of a research meditation on the nature of these mathematical objects. I've been meaning to write a blog post about this project for years. Maybe someday...

**Comment by trsh** [comment]
OK, fear enough.
